### ISSUE TITLE
Include an example on how to use with Stasis

### ISSUE THREAD

**Issue by bcardarella** [winton/smart_asset#11]
Maybe I missed it in the Readme but it seems Rails and Sinatra are covered but not Stasis.

**Comment by bcardarella** [comment]
Although after looking over the stasis adapter code it seems to register itself as longas Stasis is available.

No tests though?

**Comment by atomical** [comment]
Did you get it to work?  I'm getting an error:

gems/smart_asset-0.5.11/lib/smart_asset.rb:24:in `compress': undefined method`[]' for nil:NilClass
