### ISSUE TITLE
Permissions for Closure Compiler Jar Appear Incorrect

### ISSUE THREAD

**Issue by gordonbanderson** [winton/smart_asset#2]
Upon installing on Ubuntu and running (once correctly configured) I saw this error:

Unable to access jarfile /usr/lib/ruby/gems/1.8/gems/smart_asset-0.5.3/bin/closure_compiler.jar

Changing the permission on that jar file to 755 instead of 644 appears to resolve the problem

**Comment by dcu** [comment]
I am having this issue too

**Comment by dcu** [comment]
fix permissions for clousure compiler. closed by d4f1e1a3c637eb8f8562ad7d1947f48cb79d0ffd

Signed-off-by: David A. Cuadrado &lt;krawek@gmail.com&gt;
